chore: add rust-libp2p maintainers to if-watch
libp2p/github-mgmt pull request #261
Opened 2024-11-11 11:42 UTC by jxs

### Summary

2024-11-11 11:53 UTC, galargh requested changes

2024-11-11 12:26 UTC, jxs commented on github/libp2p.yml
> +        - rust-libp2p Maintainers
Thanks Piotr! updated

2024-11-11 23:19 UTC, jxs commented
thanks Piotr, udpdated!

2024-11-12 05:59 UTC, galargh approved these changes

2024-11-12 05:59 UTC, merged